### ISSUE TITLE
validation and validation runner

### ISSUE THREAD

**Issue by johndavedecano** [svelte-society-ph/svelte-validation#1]
## 📝 Description

Create validation internal classes

## ⚙️ Component

Specify the component/s to be added or edited.

## 📋 Todo:

- [ ] Added validation class
- [ ] Added validation runner class
- [ ] Added initial structure for component
- [ ] Added initial .github pull request templates
